# Generated by Django 5.2.8 on 2026-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_title_product_name_remove_product_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
