# Generated by Django 5.2.8 on 2026-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_productimage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="Ron", max_length=100),
        ),
    ]
